# Generated by Django 4.2 on 2023-04-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=123, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=123, verbose_name='Фамилия')),
                ('age', models.DateTimeField(verbose_name='Дата рождения')),
                ('address', models.CharField(max_length=123, verbose_name='Адрес по прописке')),
                ('real_address', models.CharField(max_length=123, verbose_name='Фактический адрес')),
                ('education', models.CharField(max_length=123, verbose_name='В каком колледже, техникуме лицее вы учитесь?')),
                ('course', models.PositiveIntegerField(verbose_name='На каком вы курсе')),
                ('speciality', models.CharField(max_length=123, verbose_name='Cпециальность')),
                ('contact_dad', models.CharField(max_length=123, verbose_name='Контакты отца')),
                ('contact_mam', models.CharField(max_length=123, verbose_name='Контакты отца')),
                ('comment', models.TextField(verbose_name='Коментарий')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='NewsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('image', models.ImageField(upload_to='news/images', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_date'],
            },
        ),
    ]
