# Generated by Django 4.2 on 2023-04-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='middle_name',
            field=models.CharField(default=1, max_length=123, verbose_name='Отчество'),
            preserve_default=False,
        ),
    ]
