# Generated by Django 4.2 on 2023-04-17 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_concursmodel_eventmodel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='contact',
            field=models.CharField(default=1, max_length=123, verbose_name='Контакты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Электронная почта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Актив'),
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.city', verbose_name='Город'),
        ),
    ]
